version: 0.2

env:
  variables:
    # リポジトリのURL（タグなし）を定義
    ECR_REPO_URL: "241706223331.dkr.ecr.ap-northeast-1.amazonaws.com/cth1-repo"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 241706223331.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build --platform linux/amd64 -t $ECR_REPO_URL:latest .
  post_build:
    commands:
      - docker push $ECR_REPO_URL:latest
      - printf '[{"name":"container-test-app","imageUri":"%s"}]' $ECR_REPO_URL:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
